# Generated by Django 6.0.3 on 2026-05-17 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Cidade❌',
                'verbose_name_plural': 'Cidades❌',
            },
        ),
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tipo', models.CharField(blank=True, choices=[('leitura', 'Leitura'), ('teatro', 'Teatro'), ('tuna', 'Tuna')], max_length=20, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='clubes/')),
            ],
            options={
                'verbose_name': 'Clube',
                'verbose_name_plural': 'Clubes Culturais',
            },
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='laboratorio/')),
                ('botao_texto', models.CharField(default='Ver atividades', max_length=100)),
                ('botao_link', models.CharField(default='#', max_length=255)),
            ],
            options={
                'verbose_name': 'Laboratório',
            },
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('nivel', models.CharField(choices=[('admin', 'Admin'), ('moderador', 'Moderador'), ('user', 'User')], default='user', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilizador',
                'verbose_name_plural': 'Utilizadores',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_evento', models.DateField(blank=True, null=True)),
                ('local', models.CharField(blank=True, max_length=150, null=True)),
                ('tipo_evento', models.CharField(blank=True, max_length=100, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cidade')),
                ('clube', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.clube')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Agenda Cultural',
            },
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legenda', models.CharField(blank=True, max_length=150, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='galeria/')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.evento')),
            ],
            options={
                'verbose_name': 'Galeria',
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('autor', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('capa', models.ImageField(blank=True, null=True, upload_to='livros/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clube', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='core.clube')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='noticias/')),
                ('clube', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='core.clube')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
            },
        ),
        migrations.CreateModel(
            name='SessaoLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_sessao', models.DateField(blank=True, null=True)),
                ('local', models.CharField(blank=True, max_length=150, null=True)),
                ('clube', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clube')),
                ('livro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.livro')),
            ],
            options={
                'verbose_name': 'Sessão de Leitura',
                'verbose_name_plural': 'Sessões de Leitura',
            },
        ),
    ]
