# Generated by Django 6.0.3 on 2026-05-18 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidade',
            options={'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidades'},
        ),
        migrations.RemoveField(
            model_name='livro',
            name='clube',
        ),
    ]
