# Generated by Django 6.0.3 on 2026-04-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilizador',
            options={},
        ),
        migrations.AlterModelManagers(
            name='utilizador',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
