# Generated by Django 6.0.3 on 2026-05-18 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cidade_options_remove_livro_clube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessaoleitura',
            name='clube',
        ),
    ]
