# Generated by Django 6.0.3 on 2026-04-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_utilizador_options_alter_utilizador_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='botao_link',
            field=models.CharField(default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='botao_texto',
            field=models.CharField(default='Ver atividades', max_length=100),
        ),
    ]
