# Generated by Django 6.0.3 on 2026-05-18 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_sessaoleitura_clube'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='clube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clube'),
        ),
    ]
