# Generated by Django 6.0.3 on 2026-04-19 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_clube_link_laboratorio_botao_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratorio',
            name='apresentacao',
        ),
        migrations.RemoveField(
            model_name='laboratorio',
            name='missao',
        ),
        migrations.RemoveField(
            model_name='laboratorio',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='laboratorio',
            name='objetivos',
        ),
    ]
