# Generated by Django 6.0.3 on 2026-05-18 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_livro_clube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='clube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='core.clube'),
        ),
    ]
