# Generated by Django 6.0.3 on 2026-04-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_laboratorio_apresentacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidade',
            options={'verbose_name': 'Cidade❌', 'verbose_name_plural': 'Cidades❌'},
        ),
        migrations.AlterModelOptions(
            name='clube',
            options={'verbose_name': 'Clube', 'verbose_name_plural': 'Clubes Culturais'},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Agenda Cultural'},
        ),
        migrations.AlterModelOptions(
            name='galeria',
            options={'verbose_name': 'Galeria'},
        ),
        migrations.AlterModelOptions(
            name='laboratorio',
            options={'verbose_name': 'Laboratório'},
        ),
        migrations.AlterModelOptions(
            name='livro',
            options={'verbose_name': 'Livro❌', 'verbose_name_plural': 'Livros❌'},
        ),
        migrations.AlterModelOptions(
            name='noticia',
            options={'verbose_name': 'Notícia❌', 'verbose_name_plural': 'Notícias❌'},
        ),
        migrations.AlterModelOptions(
            name='sessaoleitura',
            options={'verbose_name': 'Sessão de Leitura❌', 'verbose_name_plural': 'Sessões de Leitura❌'},
        ),
        migrations.AlterModelOptions(
            name='utilizador',
            options={'verbose_name': 'Utilizador', 'verbose_name_plural': 'Utilizadores'},
        ),
        migrations.AddField(
            model_name='clube',
            name='imagem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
