# Generated by Django 6.0.3 on 2026-05-24 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_livro_clube'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoTeatro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_sessao', models.DateField(blank=True, null=True)),
                ('local', models.CharField(blank=True, max_length=150, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='teatro/')),
                ('clube', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_teatro', to='core.clube')),
            ],
            options={
                'verbose_name': 'Sessão de Teatro',
                'verbose_name_plural': 'Sessões de Teatro',
            },
        ),
    ]
