# Generated by Django 6.0.3 on 2026-05-14 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cidade_options_alter_clube_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='clube',
            name='tipo',
            field=models.CharField(blank=True, choices=[('leitura', 'Leitura'), ('teatro', 'Teatro'), ('tuna', 'Tuna')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='clube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='core.clube'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='clube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.clube'),
        ),
    ]
