# Generated by Django 6.0.3 on 2026-05-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_clube_slug_clube_tipo_livro_clube_alter_evento_clube'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={'verbose_name': 'Livro', 'verbose_name_plural': 'Livros'},
        ),
        migrations.AlterModelOptions(
            name='sessaoleitura',
            options={'verbose_name': 'Sessão de Leitura', 'verbose_name_plural': 'Sessões de Leitura'},
        ),
        migrations.AlterField(
            model_name='clube',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='clubes/'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='livros/'),
        ),
    ]
