# Generated by Django 6.0.3 on 2026-05-26 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sessaoteatro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessaoleitura',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sessaoteatro',
            options={},
        ),
        migrations.RemoveField(
            model_name='sessaoteatro',
            name='clube',
        ),
        migrations.AddField(
            model_name='sessaoleitura',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cidade'),
        ),
        migrations.AddField(
            model_name='sessaoteatro',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cidade'),
        ),
    ]
