# Generated by Django 6.0.3 on 2026-05-27 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_sessaoleitura_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={},
        ),
        migrations.RemoveField(
            model_name='evento',
            name='clube',
        ),
        migrations.AddField(
            model_name='evento',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='eventos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evento',
            name='vagas',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='sessaoleitura',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='sessoes_leitura', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessaoleitura',
            name='vagas',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='sessaoteatro',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='sessoes_teatro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessaoteatro',
            name='vagas',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
