# Generated by Django 6.0.3 on 2026-05-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_livro_options_alter_sessaoleitura_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galeria',
            old_name='titulo',
            new_name='legenda',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='caminho_imagem',
        ),
        migrations.AddField(
            model_name='galeria',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/'),
        ),
    ]
