# Generated by Django 6.0.3 on 2026-05-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_titulo_galeria_legenda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/'),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='laboratorio/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/'),
        ),
    ]
