# Generated by Django 6.0.3 on 2026-06-02 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_evento_options_remove_evento_clube_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='participantes',
        ),
        migrations.RemoveField(
            model_name='sessaoleitura',
            name='participantes',
        ),
        migrations.RemoveField(
            model_name='sessaoteatro',
            name='participantes',
        ),
        migrations.AlterField(
            model_name='evento',
            name='vagas',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='sessaoteatro',
            name='vagas',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='core.evento')),
                ('sessao_leitura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='core.sessaoleitura')),
                ('sessao_teatro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='core.sessaoteatro')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('utilizador', 'evento'), name='unique_evento_inscricao'), models.UniqueConstraint(fields=('utilizador', 'sessao_leitura'), name='unique_leitura_inscricao'), models.UniqueConstraint(fields=('utilizador', 'sessao_teatro'), name='unique_teatro_inscricao')],
            },
        ),
    ]
