# Generated by Django 6.0.3 on 2026-06-06 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_evento_participantes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembroClube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoClube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('motivacao', models.TextField()),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('aceite', 'Aceite'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='inscricao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('evento__isnull', False), ('sessao_leitura__isnull', True), ('sessao_teatro__isnull', True)), models.Q(('evento__isnull', True), ('sessao_leitura__isnull', False), ('sessao_teatro__isnull', True)), models.Q(('evento__isnull', True), ('sessao_leitura__isnull', True), ('sessao_teatro__isnull', False)), _connector='OR'), name='exactly_one_activity'),
        ),
        migrations.AddField(
            model_name='membroclube',
            name='clube',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clube'),
        ),
        migrations.AddField(
            model_name='membroclube',
            name='utilizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedidoclube',
            name='clube',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clube'),
        ),
        migrations.AddField(
            model_name='pedidoclube',
            name='utilizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='membroclube',
            unique_together={('utilizador', 'clube')},
        ),
        migrations.AlterUniqueTogether(
            name='pedidoclube',
            unique_together={('utilizador', 'clube')},
        ),
    ]
