# Generated by Django 6.0.3 on 2026-05-15 16:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_evento_imagem_alter_laboratorio_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
