# Generated by Django 6.0.3 on 2026-06-06 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_membroclube_pedidoclube_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='clube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.clube'),
        ),
    ]
