# Generated by Django 6.0.3 on 2026-05-16 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_livro_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={'ordering': ['-created_at'], 'verbose_name': 'Livro', 'verbose_name_plural': 'Livros'},
        ),
        migrations.AlterModelOptions(
            name='noticia',
            options={'verbose_name': 'Notícia', 'verbose_name_plural': 'Notícias'},
        ),
        migrations.RemoveField(
            model_name='clube',
            name='link',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='clube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='core.clube'),
        ),
    ]
