# Generated by Django 6.0.3 on 2026-06-06 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_membroclubeleitura_membroclubeteatro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Laboratorio',
        ),
        migrations.AlterUniqueTogether(
            name='membroclubeleitura',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='membroclubeleitura',
            name='clube',
        ),
        migrations.RemoveField(
            model_name='membroclubeleitura',
            name='utilizador',
        ),
        migrations.AlterUniqueTogether(
            name='membroclubeteatro',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='membroclubeteatro',
            name='clube',
        ),
        migrations.RemoveField(
            model_name='membroclubeteatro',
            name='utilizador',
        ),
        migrations.AlterUniqueTogether(
            name='pedidoclube',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pedidoclube',
            name='clube',
        ),
        migrations.RemoveField(
            model_name='pedidoclube',
            name='utilizador',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='clube',
        ),
        migrations.DeleteModel(
            name='MembroClube',
        ),
        migrations.DeleteModel(
            name='MembroClubeLeitura',
        ),
        migrations.DeleteModel(
            name='MembroClubeTeatro',
        ),
        migrations.DeleteModel(
            name='PedidoClube',
        ),
    ]
