# Generated by Django 6.0.3 on 2026-06-06 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_laboratorio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legenda', models.CharField(blank=True, max_length=150, null=True)),
                ('imagem', models.ImageField(upload_to='galeria/home/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Galeria Home',
                'verbose_name_plural': 'Galeria Home',
            },
        ),
        migrations.AlterField(
            model_name='noticia',
            name='conteudo',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data_publicacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(upload_to='noticias/'),
        ),
        migrations.AlterField(
            model_name='sessaoleitura',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cidade'),
        ),
        migrations.AlterField(
            model_name='sessaoleitura',
            name='data_sessao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sessaoleitura',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.livro'),
        ),
        migrations.AlterField(
            model_name='sessaoleitura',
            name='local',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='sessaoteatro',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cidade'),
        ),
        migrations.AlterField(
            model_name='sessaoteatro',
            name='data_sessao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sessaoteatro',
            name='descricao',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='sessaoteatro',
            name='imagem',
            field=models.ImageField(upload_to='teatro/'),
        ),
        migrations.AlterField(
            model_name='sessaoteatro',
            name='local',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='GaleriaTeatro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legenda', models.CharField(blank=True, max_length=150, null=True)),
                ('imagem', models.ImageField(upload_to='galeria/teatro/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria_teatro', to='core.clube')),
            ],
            options={
                'verbose_name': 'Galeria Teatro',
                'verbose_name_plural': 'Galeria Teatro',
            },
        ),
        migrations.DeleteModel(
            name='Galeria',
        ),
    ]
