# Generated by Django 6.0.3 on 2026-06-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_galeriahome_alter_noticia_conteudo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.ImageField(upload_to='livros/'),
        ),
    ]
