# Generated by Django 6.0.3 on 2026-06-06 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_livro_autor_alter_livro_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeriateatro',
            name='clube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galeria_teatro', to='core.clube'),
        ),
    ]
