# Generated by Django 6.0.3 on 2026-06-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_galeriateatro_clube'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legenda', models.CharField(blank=True, max_length=150, null=True)),
                ('imagem', models.ImageField(upload_to='galeria/teatro/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Galeria Teatro',
                'verbose_name_plural': 'Galeria Teatro',
            },
        ),
        migrations.DeleteModel(
            name='GaleriaHome',
        ),
        migrations.DeleteModel(
            name='GaleriaTeatro',
        ),
    ]
