# Generated by Django 6.0.3 on 2026-06-06 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_galeria_delete_galeriahome_delete_galeriateatro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={},
        ),
        migrations.AlterModelOptions(
            name='noticia',
            options={},
        ),
        migrations.AlterField(
            model_name='livro',
            name='clube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='core.clube'),
        ),
    ]
