# Generated by Django 6.0.3 on 2026-06-06 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_livro_options_alter_noticia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='clube',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='core.clube'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='clube',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='core.clube'),
        ),
    ]
